# Generated by Django 5.1.1 on 2024-12-20 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardman', '0003_alter_category_image_alter_type_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='ProductType',
        ),
    ]
