# Generated by Django 5.1.1 on 2024-12-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardman', '0005_rename_category_id_producttype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_img/'),
        ),
    ]
