# Generated by Django 5.1.1 on 2025-01-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardman', '0007_alter_producttype_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='membership_price',
            new_name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_img/'),
        ),
        migrations.AddField(
            model_name='product',
            name='membership_discount_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_img/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_img/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_img/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
