# Generated by Django 5.1.1 on 2025-01-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardman', '0008_rename_membership_price_product_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
